### ISSUE TITLE
Team Card Section

### ISSUE THREAD

**Issue by Kraniket901** [NITRR-Technocracy/TC-Frontend#13]
# Points: 5

1. Go to this Page: [Team Page](https://www.cognizance.org.in/team)
2. Clone the Head's Card
3. Add the Animations
4. Make it Responsive
5. Make a Component : <HeadCard/> inside src/components/HeadCard.js

NOTE: Do not change anything else. Just add one Component and / or one css file in the same dir.

**Comment by dxxwakr** [comment]
sir may I be assigned to this issue

**Comment by Kraniket901** [comment]
Yes Sure ! Go Ahead.

**Comment by Kraniket901** [comment]
@dxxwakr PLease pull the latest commit, you would see that i have created new Page in : pages/TeamPage.js
Use your HeadCard component there. Make sure to map it with JSON data which i have provided in : assets/heads_Data.js
run it on Local Host and Check it's responsiveness

**Comment by dxxwakr** [comment]
ok Sir !
