### ISSUE TITLE
Spons Section

### ISSUE THREAD

**Issue by Kraniket901** [NITRR-Technocracy/TC-Frontend#14]
# Points: 2

1. Go to this Page: [Insta](https://www.instagram.com/nitrr.aavartan/)
2. Search for All the sponsors which came last year.
3. Check whether it is present in our json data or not.
4. If no, add it. (Use png Format)

NOTE: Just add spons png in src/assets/spons_images, update json file in src/assets/spons_data.js. Do not change anything else

**Comment by probot-codes** [comment]
May I work on this issue, please?

**Comment by Kraniket901** [comment]
Yes Sure !

**Comment by Team-Technocracy** [comment]
@probot-codes Good !!
