### ISSUE TITLE
Our Journey : Mobile Responsive

### ISSUE THREAD

**Issue by Kraniket901** [NITRR-Technocracy/TC-Frontend#23]
# Points: 2

1. Check the responsiveness of Our Journey Section
2. Give padding or Margin in the side (left and right)
3. You can make the Journey box bit smaller (Only if it looks good)

NOTE: 1. Before commiting, check whether ur styling is not effecting other components. 2. Only make changes inside media query

**Comment by student-mayank** [comment]
Can I work on it?

**Comment by Kraniket901** [comment]
Go Ahead !

**Comment by Kraniket901** [comment]
Done and Dusted

**Comment by Kraniket901** [comment]
Done and Dusted !!
