### ISSUE TITLE
FAQ Section : Responsiveness

### ISSUE THREAD

**Issue by Kraniket901** [NITRR-Technocracy/TC-Frontend#24]
# Points : 2

1. Check the responsiveness of FAQ Section (in Galaxy Fold Dimention)
2. Remove Top and Bottom Padding of section#faq
3. Give lil bit padding to the sides (.faq_col) (left and right) so that it looks good.
4. remove margin bottom of .faq_col

NOTE: 1. Before commiting, check whether ur styling is not effecting other components. 2. Only make changes inside media query

**Comment by probot-codes** [comment]
Sir, may I work on this issue please?

**Comment by Team-Technocracy** [comment]
Yes Please !!
