### ISSUE TITLE
Contact Us : Responsiveness

### ISSUE THREAD

**Issue by Kraniket901** [NITRR-Technocracy/TC-Frontend#25]
# Points : 2

1. Check the responsiveness of Contact Section (in Galaxy Fold Dimention)
2. make #contact padding to : 14px 0 14px 0 ;
3. Give lil bit padding to the sides (either ul or li) (left and right) so that it looks good.
4. decrease the height of input boxes.
5. Make "Send message" button smaller

NOTE: 1. Before commiting, check whether ur styling is not effecting other components. 2. Only make changes inside media query

**Comment by Nehilsa2** [comment]
sir may i work on this issue?

**Comment by Kraniket901** [comment]
Why Not !!

**Comment by Team-Technocracy** [comment]
Done
