### ISSUE TITLE
Footer : Responsiveness

### ISSUE THREAD

**Issue by Kraniket901** [NITRR-Technocracy/TC-Frontend#26]
# Points : 3

1. Check the responsiveness of Footer Section (in Galaxy Fold Dimension)

2. Find this class (name may not be same), and make margin and padding = 0
.Footer_fquotessec__6txqW {
    margin-top: 3rem; //make this zero
    margin-left: 2rem; //make this zero
}

3. media (max-width: 900px)
.Footer_footercol__KuUCN {
    width: 50%;
    margin-bottom: 30px; //make this zero
}

4. list items should be in center :
.Footer_footercol__KuUCN ul li {
    display: flex;
    align-items: center; //add this line
    justify-content: center; //add this line
}

5. Give lil bit of padding on both sides of whole footer so that items don't touch the margin in any dimension.
6. Change the absolute or fixed position of # ScrollToTop button by changing it's position little but downwards.
@media (max-width: 768px)
.metaportal_fn_totop {
    right: 20px; //Decrease This till it looks good
    bottom: 20px; //Decrease This ill it looks good
}

NOTE: 1. Before commiting, check whether ur styling is not effecting other components. 2. Only make changes inside media query

**Comment by probot-codes** [comment]
May I work on this issue please?

**Comment by Team-Technocracy** [comment]
Ya Sure !!
