### ISSUE TITLE
Description & Navigation Responsiveness

### ISSUE THREAD

**Issue by Kraniket901** [NITRR-Technocracy/TC-Frontend#28]
# Points : 2

1. search in App.css ".fn_cs_desc p"

.fn_cs_desc p {
    margin: 0;
    font-size: 20px;  // Change to 15px
    line-height: 30px; //Change to 20px
    margin-bottom: 41px;
}

2. Align all list items of Layout/Navigation.js for media query only (Mobile View) to center.
Now, they all are not aligned in mobile view

**Comment by Nehilsa2** [comment]
sir may i work on this issue please?

**Comment by Team-Technocracy** [comment]
Yes!! But please dont make new classname, ids. Inspect the elements, hover on it to get it's classname or id, search that id or classname in App.css and then change it.

All the best
